name: Continuous integration
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  ci:
    uses: SAGARobotics/SagaWorkflows/.github/workflows/ci.yml@v3.3
    with:
      release: 'false'
      disable-checks: 'true'
      runs-on: '["ubuntu-latest"]'
    secrets:
      pat-token: ${{ secrets.CI_PAT_PUBLIC }}
      repo-user: ${{ secrets.SAGA_REPO_PUBLIC_WRITE_USER }}
      repo-pass: ${{ secrets.SAGA_REPO_PUBLIC_WRITE_PASS }}
